# Generated by Django 5.1.6 on 2025-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_completed_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
